apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: jboss/keycloak:latest
        ports:
        - containerPort: 8080
        env:
          - name: KEYCLOAK_USER
            valueFrom:
                secretKeyRef:
                  name: auth-config
                  key: KEYCLOAK_USER
          - name: KEYCLOAK_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: auth-config
                  key: KEYCLOAK_PASSWORD
          - name: DB_VENDOR
            value: MYSQL
          - name: DB_ADDR
            value: auth-db-service
          - name: MYSQL_DATABASE
            value: keycloak
          - name: DB_USER
            valueFrom:
                secretKeyRef:
                  name: auth-db-root-pw
                  key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: auth-db-root-pw
                  key: MYSQL_PASSWORD
          - name: DB_PORT
            value: "3306"
          - name: JDBC_PARAMS
            value: useSSL=false
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"